version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:${jenkins_version_tag}
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 8080:8080
    container_name: jenkins-${jenkins_version_tag}
    volumes:
      - /usr/local/src/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
